name: Sonic Platforms
favicon: null
layout_spectrum: 0.76478
typography_spectrum: 0.57487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#aa6a19'
    - '#eec82e'
    - '#5f4443'
    - '#f0fcdd'
  brandStrength: 0.3125
  lightness: 0.7840370233170688
  saturation: 0.06427900562994182
  rhythmicContrast: 0.004163974430412054
purpose: []
