name: Sonic Platforms
favicon: null
layout_spectrum: 0.3118577825371176
typography_spectrum: 0.7127166190184653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20237358659505844
  lightness: 0.7840370233170688
  saturation: 0.06427900562994182
  rhythmicContrast: 0.004163974430412054
purpose: []
